>P1;3UR8

-----------------------------------QPIGVCYGKIANNLP
SDQDVIKLYNANNIKKMRIYYPHTNVFNALKGSNIEIILDVPNQDLEALA
NPSNANGWVQDNIRNHFPDVKFKYIAVGNEVDPG-RESGKYARFVGPAME
NIYNALSSAGLQNQIKVSTSTYSGLLTNTYPPRDSIFREEYKSFINPIIG
FLARHNLPLLANIYPYFGHIDNTNAVPLSYALFN---------QTGYQNL
FDALVDSMYFATEKLGGQNIEIIVSESGWPSEGHPAATLKNARTYYTNLI
NHVKRGAGTPKKPGKTIETYLFAMFDENEKKGEASEKHFGLFNPDQRPKY
QLNFN------LNHHHH----------
*
>P1;sp|P52407.2|E13B_HEVBR

MAISSSTSGTSSSFPSRTTVMLLLFFFAASVGITDAQVGVCYGMQGNNLP
PVSEVIALYKKSNITRMRIYDPNRAVLEALRGSNIELILGVPNSDLQSLT
NPSNAKSWVQKNVRGFWSSVLFRYIAVGNEISPVNRGTAWLAQFVLPAMR
NIHDAIRSAGLQDQIKVSTAIDLTLVGNSYPPSAGAFRDDVRSYLDPIIG
FLSSIRSPLLANIYPYFTYAYNPRDISLPYALFTSPSVVVWDGQRGYKNL
FDATLDALYSALERASGGSLEVVVSESGWPSAGAFAATFDNGRTYLSNLI
QHVKG--GTPKRPNRAIETYLFAMFDEN-KKQPEVEKHFGLFFPNKWQKY
NLNFSAEKNWDISTEHNATILFLKSDM
*
